<table class="dataframe datatable">
  <thead>
    <tr style="text-align: right;">
      <th>year</th>
      <th style="min-width: 40%;">Country of origin</th>
      <th style="min-width: 12.0%;">2022</th>
      <th style="min-width: 12.0%;">2023</th>
      <th style="min-width: 12.0%;">total</th>
      <th style="min-width: 12.0%;">change</th>
      <th style="min-width: 12.0%;">perc_of_total</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th></th>
      <td>Unknown</td>
      <td>606</td>
      <td>901</td>
      <td>1,507</td>
      <td>48.7%</td>
      <td>0.28</td>
    </tr>
    <tr>
      <th></th>
      <td>China</td>
      <td>735</td>
      <td>739</td>
      <td>1,474</td>
      <td>0.5%</td>
      <td>0.27</td>
    </tr>
    <tr>
      <th></th>
      <td>Italy</td>
      <td>55</td>
      <td>540</td>
      <td>595</td>
      <td>881.8%</td>
      <td>0.11</td>
    </tr>
    <tr>
      <th></th>
      <td>Germany</td>
      <td>147</td>
      <td>244</td>
      <td>391</td>
      <td>66.0%</td>
      <td>0.07</td>
    </tr>
    <tr>
      <th></th>
      <td>France</td>
      <td>86</td>
      <td>163</td>
      <td>249</td>
      <td>89.5%</td>
      <td>0.05</td>
    </tr>
    <tr>
      <th></th>
      <td>Poland</td>
      <td>27</td>
      <td>118</td>
      <td>145</td>
      <td>337.0%</td>
      <td>0.03</td>
    </tr>
    <tr>
      <th></th>
      <td>Spain</td>
      <td>25</td>
      <td>87</td>
      <td>112</td>
      <td>248.0%</td>
      <td>0.02</td>
    </tr>
    <tr>
      <th></th>
      <td>Turkey</td>
      <td>73</td>
      <td>67</td>
      <td>140</td>
      <td>-8.2%</td>
      <td>0.03</td>
    </tr>
    <tr>
      <th></th>
      <td>UK</td>
      <td>45</td>
      <td>63</td>
      <td>108</td>
      <td>40.0%</td>
      <td>0.02</td>
    </tr>
    <tr>
      <th></th>
      <td>Japan</td>
      <td>47</td>
      <td>43</td>
      <td>90</td>
      <td>-8.5%</td>
      <td>0.02</td>
    </tr>
  </tbody>
</table>
